### ISSUE TITLE
Backstack is not maintaining properly in bottom navigation

### ISSUE THREAD

**Issue by FazalHussain** [mitchtabian/Open-API-Android-App#13]
I have noticed that backstack of bottom view is not handled properly. If you navigate multiple times in bottom navigation you have duplicated fragment in back stack

How to reproduce

Home -> Account -> create Blog -> Home -> Account

**Comment by FazalHussain** [comment]
Any update?

**Comment by mitchtabian** [comment]
Looking into it now.

**Comment by mitchtabian** [comment]
The fragments are not stacking. That is the intended behavior. When pressing back it goes:
Home < CreateBlog < Home < Closed

Home is the only one that will ever be shown twice because the app must exit from Home.
