### ISSUE TITLE
Restore Search Bar State

### ISSUE THREAD

**Issue by dadocsis** [mitchtabian/Open-API-Android-App#14]
In the Blog Fragment I noticed the blog search text disappears during a configuration change even through the search query is restored.

Steps to reproduce..
- Login and land on the Blog Fragment.
- Perform a search via the tool bar
- rotate device
- notice the search text in the toolbar disappears.

Great course and app btw!

**Comment by ch8n** [comment]
Hi, @mitchtabian I would like to contribute to this.

**Comment by mitchtabian** [comment]
fixed https://github.com/mitchtabian/Open-API-Android-App/commit/51d552dee89da66517464e4c2162d89291be925b
