### ISSUE TITLE
Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\NetworkBoundResource.kt: (37, 21): Not enough information to infer type variable ViewState

### ISSUE THREAD

**Issue by Pratyush149** [mitchtabian/Open-API-Android-App#15]
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:writeDebugApplicationId UP-TO-DATE
> Task :app:generateSafeArgsDebug UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:mergeLibDexDebug
> Task :app:processDebugManifestForPackage
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions
> Task :app:mergeExtDexDebug
> Task :app:processDebugResources
> Task :app:kaptGenerateStubsDebugKotlin UP-TO-DATE
> Task :app:kaptDebugKotlin UP-TO-DATE

> Task :app:compileDebugKotlin FAILED
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\NetworkBoundResource.kt: (36, 17): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\NetworkBoundResource.kt: (37, 21): Not enough information to infer type variable ViewState
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\NetworkBoundResource.kt: (47, 21): Not enough information to infer type variable ViewState
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\NetworkBoundResource.kt: (58, 25): Not enough information to infer type variable ViewState
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\auth\AuthRepositoryImpl.kt: (119, 13): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\auth\AuthRepositoryImpl.kt: (120, 17): Not enough information to infer type variable ViewState
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\auth\AuthRepositoryImpl.kt: (212, 13): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\repository\auth\AuthRepositoryImpl.kt: (213, 17): Not enough information to infer type variable ViewState
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\ui\auth\AuthViewModel.kt: (62, 35): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\ui\main\account\AccountViewModel.kt: (69, 39): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\ui\main\blog\viewmodel\BlogViewModel.kt: (45, 13): Type mismatch: inferred type is String? but String was expected
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\ui\main\blog\viewmodel\BlogViewModel.kt: (150, 43): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\ui\main\create_blog\CreateBlogViewModel.kt: (66, 39): Not enough information to infer type variable T
e: D:\android_code_repo\latest arch\Open-API-Android-App-MVI\app\src\main\java\com\codingwithmitch\openapi\util\BottomNavController.kt: (116, 27): Unresolved reference: backStack

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
27 actionable tasks: 9 executed, 18 up-to-date

**Comment by mitchtabian** [comment]
Just specify the type
