### ISSUE TITLE
Not enough information to infer type variable T

### ISSUE THREAD

**Issue by razaghimahdi** [mitchtabian/Open-API-Android-App#18]
so when i use emit for buildError  then i get: Not enough information to infer type variable T

for example in AuthRepositoryImpl.kt:

            emit(
                buildError(
                    loginFieldErrors,
                    UIComponentType.Dialog(),
                    stateEvent
                )
            )

why this happening?

**Comment by mitchtabian** [comment]
Specify the type. 
```kotlin
emit(
    buildError<TheType>(
        loginFieldErrors,
        UIComponentType.Dialog(),
        stateEvent
    )
)
```
