### ISSUE TITLE
wrong error message showing in dialog (new source)

### ISSUE THREAD

**Issue by razaghimahdi** [mitchtabian/Open-API-Android-App#21]
as u see in this screenshot i get wrong error message which it shouldn't show like this to user also i guess whole project has this bug because i saw it in different fragments

![Screenshot_1627025333](https://user-images.githubusercontent.com/61207818/126750465-899769ce-92f1-4379-9000-5cf8d130d4f2.png)

**Comment by mitchtabian** [comment]
Fixed for login. It was a server-side issue.
