### ISSUE TITLE
multi dialog popup while offline paging(new source)

### ISSUE THREAD

**Issue by razaghimahdi** [mitchtabian/Open-API-Android-App#22]
as u see this dialog popup(screenshot) when i get data from network then i turn on airplane mode then  while paging by offline  too many dialogs popup which there r the same i mean they just repeat and repeat too many times and i have no clue why this happend but probably it has something do with these:
```kotlin 

    private fun removeHeadFromQueue() {
        Log.i(TAG, "removeHeadFromQueue: ")
        state.value?.let { state ->
            try {
                val queue = state.queue
                queue.remove() // can throw exception if empty
                this.state.value = state.copy(queue = queue)
            } catch (e: Exception) {
                Log.d(TAG, "removeHeadFromQueue: Nothing to remove from DialogQueue")
            }
        }
    }

    private fun appendToMessageQueue(stateMessage: StateMessage){
        Log.i(TAG, "appendToMessageQueue: ")
        state.value?.let { state ->
            val queue = state.queue
            if(!stateMessage.doesMessageAlreadyExistInQueue(queue = queue)){
                if(!(stateMessage.response.uiComponentType is UIComponentType.None)){
                    queue.add(stateMessage)
                    this.state.value = state.copy(queue = queue)
                }
            }
        }
    }

```

b/c they make log too many times

![Screenshot_1627025832](https://user-images.githubusercontent.com/61207818/126751250-73967af6-4961-4d18-8939-0f2b12a28f05.png)

**Comment by shipsywor** [comment]
Same happens for me. I was waiting to file issues as the app was updated very frequently almost daily. 

There a lot of bugs in this refactor.

**Comment by Morons** [comment]
Yes the AppDebug shows repeatedly 
D/AppDebug: BlogFragment: attempting to load next page...
D/AppDebug: removeHeadFromQueue: Nothing to remove from DialogQueue

**Comment by mitchtabian** [comment]
https://github.com/mitchtabian/Open-API-Android-App/commit/2499624cee774fc9aa3498d67adeb174bd77ec84
