### ISSUE TITLE
caching list doesnt work anymore (new soruce)

### ISSUE THREAD

**Issue by razaghimahdi** [mitchtabian/Open-API-Android-App#23]
so first time i opened app by network then i turn on airplane mode and restart app, then after poping up dialog,it showed me blank  fragment with no item 

![Screenshot_1627027079](https://user-images.githubusercontent.com/61207818/126753253-7e766b4c-c6df-497b-b898-5f0be0cc8cda.png)
![Screenshot_1627027086](https://user-images.githubusercontent.com/61207818/126753305-e83868d0-32b9-47a1-bdd1-c77a5428aaa1.png)

**Comment by mitchtabian** [comment]
https://github.com/mitchtabian/Open-API-Android-App/commit/2499624cee774fc9aa3498d67adeb174bd77ec84
