### ISSUE TITLE
Email seems to be gone on Profile

### ISSUE THREAD

**Issue by Zhuinden** [mitchtabian/Open-API-Android-App#5]
![image](https://user-images.githubusercontent.com/11718392/69895360-1a5dce00-132e-11ea-9570-1301a7ccc163.png)

I'm pretty sure this used to say `aaaaa@aaa.aaa` before.

I modified nothing other than [testing the app](https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399).

**Comment by mitchtabian** [comment]
Should be related to [Issue #4](https://github.com/mitchtabian/Open-API-Android-App/issues/4).

Process death leads to all kinds of problems.
