### ISSUE TITLE
Please can you give example for DialogFragment() with Dagger

### ISSUE THREAD

**Issue by ghost** [mitchtabian/Open-API-Android-App#6]
Ex.
BaseDialogFragment : **DialogFragment()**, Injectable

**Comment by souravpany** [comment]
you can do the way as follows :

1st Step - 

create a kotlin class as - BaseDialog fragment then in that do as follows - 

**BaseDialogFragment : DialogFragment()**

2nd Step -
Create module and components for dialog fragment then rebuild the project - follow the code as follows - 

**DialogFragmentModule** - here you can provide the method like your view model, layout manager functions etc.
**DialogFragmentComponent** - here you can add the scope and components with inject methods.

**Comment by mitchtabian** [comment]
This is not an issue. Please don't request videos/features as an issue.

**Comment by ghost** [comment]
I wont do it again. Sorry for that... plz tell me how should i reach you.
Is there any dedicated medium for paid members...

**Comment by ghost** [comment]
plz can you do a video feature for DialogFragment() ?
