### ISSUE TITLE
Just clarification 

### ISSUE THREAD

**Issue by ghost** [mitchtabian/Open-API-Android-App#7]
Instead of adding all fragment in MainFragmentBuildersModule. Can we add 

1. BaseAccountFragment
2. BaseBlogFragment
3. BaseCreateBlogFragment

![image](https://user-images.githubusercontent.com/22938251/73352228-991cac00-4288-11ea-818e-7e661e9016d8.png)

**Comment by DJDrama** [comment]
No That does not work.
You will get an exception 
java.lang.IllegalArgumentException: No injector factory bound for Class
