### ISSUE TITLE
Deleted posts still exists on other user devices and displays error on viewing.

### ISSUE THREAD

**Issue by placeholdergit** [mitchtabian/Open-API-Android-App#9]
If the author deleted a post, ideally it should not be seen on the other user devices as well.
For example, deleting a Instagram post. The post is not view-able to other users if the author deletes it.

But, the deleted post is stored in cache in the Open API App case. This is definitely an undesirable behavior and a bug.

It would be helpful if you take action to solve this issue.

Steps to reproduce:

1. Create a post with device 'A', use emulator or device 'B' and sign in with same user and delete the post.
2. Go back to device 'A' and click on the post we just deleted using device 'B'.

[1]
![unnamed (1)](https://user-images.githubusercontent.com/58146528/74086174-62c00780-4aa6-11ea-8f56-62026f689a04.jpg)

[2]
![unnamed](https://user-images.githubusercontent.com/58146528/74086163-4b811a00-4aa6-11ea-900f-6e0dd733cb54.jpg)

**Comment by mitchtabian** [comment]
Yes the scope of the course didn't cover a cache removal strategy. You'll want to implement something where every month or so the app will check if that blog post still exists. Also at the time of getting a "Not Found" error you could confirm it doesn't exist and remove it.
